CS504
Project 4
Group 7
Members: Vishveshwar Rao, Sachin Mote, Harshith Reddy

Importing the necessary libraries required for the project

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import normalize
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import statistics as st

Reading data and checking Null values

In [32]:
bank_df=pd.read_csv(r'C:\Users\sachi\Downloads\bank.csv',delimiter=';')
features=bank_df.columns

bank_df.shape

(4521, 17)

No Null Values in the data

In [33]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


Describing data

In [34]:
bank_df.describe()

age       balance          day     duration     campaign  \
count  4521.000000   4521.000000  4521.000000  4521.000000  4521.000000   
mean     41.170095   1422.657819    15.915284   263.961292     2.793630   
std      10.576211   3009.638142     8.247667   259.856633     3.109807   
min      19.000000  -3313.000000     1.000000     4.000000     1.000000   
25%      33.000000     69.000000     9.000000   104.000000     1.000000   
50%      39.000000    444.000000    16.000000   185.000000     2.000000   
75%      49.000000   1480.000000    21.000000   329.000000     3.000000   
max      87.000000  71188.000000    31.000000  3025.000000    50.000000   

             pdays     previous  
count  4521.000000  4521.000000  
mean     39.766645     0.542579  
std     100.121124     1.693562  
min      -1.000000     0.000000  
25%      -1.000000     0.000000  
50%      -1.000000     0.000000  
75%      -1.000000     0.000000  
max     871.000000    25.000000

Describing the data including the categorical data 

In [35]:
bank_df.describe(include=object)

job  marital  education default housing  loan   contact month  \
count         4521     4521       4521    4521    4521  4521      4521  4521   
unique          12        3          4       2       2     2         3    12   
top     management  married  secondary      no     yes    no  cellular   may   
freq           969     2797       2306    4445    2559  3830      2896  1398   

       poutcome     y  
count      4521  4521  
unique        4     2  
top     unknown    no  
freq       3705  4000

Checking counts of the response variable (y column is the response variable)

In [36]:
bank_df['y'].value_counts()

no     4000
yes     521
Name: y, dtype: int64

Checking null values

In [38]:
bank_df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

Transforming categorical to numerical values using LabelEncoder function

In [39]:
#Using LabelEncoder...
data=bank_df.copy()

le_obj=LabelEncoder()

data.job=le_obj.fit_transform(data.job)
data.marital=le_obj.fit_transform(data.marital)
data.education=le_obj.fit_transform(data.education)
data.default=le_obj.fit_transform(data.default)
data.housing=le_obj.fit_transform(data.housing)
data.loan=le_obj.fit_transform(data.loan)
data.contact=le_obj.fit_transform(data.contact)
data.month=le_obj.fit_transform(data.month)
data.poutcome=le_obj.fit_transform(data.poutcome)

data.y=le_obj.fit_transform(data.y)
print(data)

      age  job  marital  education  default  balance  housing  loan  contact  \
0      30   10        1          0        0     1787        0     0        0   
1      33    7        1          1        0     4789        1     1        0   
2      35    4        2          2        0     1350        1     0        0   
3      30    4        1          2        0     1476        1     1        2   
4      59    1        1          1        0        0        1     0        2   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
4516   33    7        1          1        0     -333        1     0        0   
4517   57    6        1          2        1    -3313        1     1        2   
4518   57    9        1          1        0      295        0     0        0   
4519   28    1        1          1        0     1137        0     0        0   
4520   44    2        2          2        0     1136        1     1        0   

      day  month  duration  campaign  p

Data Normalisation using Min and Max values and Splitting the data into training and testing data.

In [40]:
#Using ColumnTransformer...
dataset=data.values
X = dataset[:,0:15] #features
y = dataset[:,16] #response

#Normalization...
X = (X - np.min(X)) / (np.max(X) - np.min(X))
print(X)

#Split...
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)

[[0.04487188 0.04460343 0.04448262 ... 0.04448262 0.04445578 0.0444692 ]
 [0.04491215 0.04456316 0.04448262 ... 0.04448262 0.04901948 0.04452289]
 [0.04493899 0.04452289 0.04449605 ... 0.04448262 0.04889867 0.04448262]
 ...
 [0.04523429 0.04459001 0.04448262 ... 0.04461685 0.04445578 0.0444692 ]
 [0.04484504 0.04448262 0.04448262 ... 0.04452289 0.04730138 0.04450947]
 [0.0450598  0.04449605 0.04449605 ... 0.04449605 0.04781144 0.04456316]]


Feature selection usinf SelectKBest function.

In [41]:
#ANOVA f-test Feature Selection...

fs = SelectKBest(score_func=f_classif, k=8) # configure to select 8 features
fs.fit(X_train, y_train) # learn relationship from training data
X_train_fs = fs.transform(X_train) # transform train input data
X_test_fs = fs.transform(X_test) # transform test input data

for i in range(len(fs.scores_)):
	print('Feature %d: %f' % (i, fs.scores_[i]))

Feature 0: 4.958839
Feature 1: 0.535927
Feature 2: 0.056736
Feature 3: 6.318238
Feature 4: 0.016698
Feature 5: 0.102734
Feature 6: 32.173637
Feature 7: 15.636245
Feature 8: 67.735857
Feature 9: 0.918195
Feature 10: 7.674686
Feature 11: 616.781195
Feature 12: 13.781887
Feature 13: 29.896941
Feature 14: 47.210185


Decision Tree Model With accuracy 87%
Using the 10-fold cross validation we found the mean accurancy to be 86.52

In [42]:
model=tree.DecisionTreeClassifier()

model.fit(X_train_fs,y_train)

yhat = model.predict(X_test_fs) #evaluate the model
accuracy = accuracy_score(y_test, yhat) #evaluate predictions
print('Accuracy: %.2f' % (accuracy*100))

print(cross_val_score(model,X,y,cv=10))
print(st.mean(cross_val_score(model,X,y,cv=10)))

Accuracy: 86.21
[0.85651214 0.85619469 0.8539823  0.87168142 0.88495575 0.87831858
 0.86504425 0.87389381 0.86725664 0.84955752]
0.8666256422278225


Random ForestClassifier Model with accuracy 89%
Using the 10-fold cross validation we found the mean accurancy to be 89.55%

In [43]:
model=RandomForestClassifier()

model.fit(X_train_fs,y_train)

yhat = model.predict(X_test_fs) 
accuracy = accuracy_score(y_test, yhat) 
print('Accuracy: %.2f' % (accuracy*100))

print(cross_val_score(model,X,y,cv=10))
print(st.mean(cross_val_score(model,X,y,cv=10)))

Accuracy: 88.77
[0.89403974 0.89380531 0.87610619 0.88495575 0.89823009 0.8960177
 0.88495575 0.91371681 0.89380531 0.90044248]
0.8949354353474379


K Nearest Neighbor Model with accuracy with 90%
Using the 10-fold cross validation we found the mean accurancy to be 88.07%

In [44]:
model=KNeighborsClassifier(n_neighbors=10)

model.fit(X_train_fs,y_train)

yhat = model.predict(X_test_fs)
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

print(cross_val_score(model,X,y,cv=10))
print(st.mean(cross_val_score(model,X,y,cv=10)))

Accuracy: 89.30
[0.88300221 0.88053097 0.86725664 0.88274336 0.87389381 0.88938053
 0.88495575 0.88938053 0.87831858 0.87831858]
0.8807780968567466


We get maximum accuracy for 41 cluster model with accuracy to be 89.12%

In [45]:
score_list={}

for k in range(1,51):
    temp_model=KNeighborsClassifier(n_neighbors=k)
    temp_model.fit(X_train_fs,y_train)
    score_list[k]=temp_model.score(X_test_fs,y_test)
    print(k,score_list[k])    

1 0.8532272325375774
2 0.8762157382847038
3 0.870026525198939
4 0.883289124668435
5 0.8841732979664014
6 0.8903625110521662
7 0.8903625110521662
8 0.8912466843501327
9 0.8956675508399646
10 0.8930150309460654
11 0.8938992042440318
12 0.8824049513704686
13 0.8903625110521662
14 0.887709991158267
15 0.8912466843501327
16 0.8912466843501327
17 0.887709991158267
18 0.8885941644562334
19 0.887709991158267
20 0.8903625110521662
21 0.8903625110521662
22 0.8912466843501327
23 0.8894783377541998
24 0.8885941644562334
25 0.887709991158267
26 0.8903625110521662
27 0.8903625110521662
28 0.8930150309460654
29 0.8921308576480991
30 0.8956675508399646
31 0.8903625110521662
32 0.8912466843501327
33 0.8912466843501327
34 0.8930150309460654
35 0.8903625110521662
36 0.8912466843501327
37 0.8921308576480991
38 0.8938992042440318
39 0.8921308576480991
40 0.8894783377541998
41 0.8912466843501327
42 0.8894783377541998
43 0.8885941644562334
44 0.887709991158267
45 0.8903625110521662
46 0.8894783377541998
47 0

Gaussian Model with accuracy with 85.39%
Using the 10-fold cross validation we found the mean accurancy to be 85.24%

In [46]:
model=GaussianNB()

model.fit(X_train_fs,y_train)

yhat = model.predict(X_test_fs)
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

print(cross_val_score(model,X,y,cv=10))
print(st.mean(cross_val_score(model,X,y,cv=10)))

Accuracy: 84.70
[0.84326711 0.82964602 0.84513274 0.86061947 0.84513274 0.88716814
 0.84292035 0.86504425 0.86061947 0.84513274]
0.852468303737131


Multinomial NB  Model with accuracy with 88.51%
Using the 10-fold cross validation we found the mean accurancy to be 88.47%

In [29]:
model=MultinomialNB()

model.fit(X_train_fs,y_train)

yhat = model.predict(X_test_fs)
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

print(cross_val_score(model,X,y,cv=10))
print(st.mean(cross_val_score(model,X,y,cv=10)))

Accuracy: 88.51
[0.88300221 0.88495575 0.88495575 0.88495575 0.88495575 0.88495575
 0.88495575 0.88495575 0.88495575 0.88495575]
0.8847603977417023


Comparison Between GaussianNB Model and MultinomialNB:
    MultinomialNB is performing better with 88.51% accuracy 
    GaussianNB is having 85.39% accuracy

Conclusion:
Out of all the models used, we get K Nearest Neighbor Model with accuracy with 90% as the best model.